<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<!--

			IMPORTANT NOTES ON VISUAL STUDIO DESIGNER:

			* The first listed framework for multi-target projects will determine the Visual Studio designer support

			* .NET Framework targets require the product's offline installer to run with the designer support option
			  even when using NuGet package references.

		-->

		<TargetFramework Label="Visual Studio 2022 Target" Condition="'$(VisualStudioVersion)' == '17.0'">net8.0-windows</TargetFramework>
		<TargetFramework Label="Default Target" Condition="'$(TargetFramework)' == ''">net10.0-windows</TargetFramework>

		<Version>26.1.0$(PreReleaseTagWithDash)</Version>

		<DefineConstants>CODE_ANALYSIS;WINFORMS;DESKTOP</DefineConstants>

		<AssemblyName>SampleBrowser</AssemblyName>
		<Product>WinForms Controls Sample Browser</Product>
		<Title>WinForms Controls Sample Browser</Title>
		<Description>Sample application to demo features of the Actipro WinForms controls.</Description>

		<AssemblyTitle>$(Title)</AssemblyTitle>

		<Company>Actipro Software LLC</Company>
		<Authors>Actipro Software LLC</Authors>
		<Copyright>Copyright (c) 2002-2026 Actipro Software LLC</Copyright>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>

		<StartupObject>ActiproSoftware.SampleBrowser.Program</StartupObject>
		<ApplicationManifest>Properties\app.manifest</ApplicationManifest>

	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Images\**\*.*" />
		<Resource Include="ProductSamples\**\*.xml" />
		<Resource Include="ProductSamples\**\Images\*.*" />
		<Resource Include="Resources\Images\**\*.*" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Definitions\**\*.langdef" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Snippets\**\*.snippet*" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\Themes\**\*.vssettings" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.html" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xml" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xsd" />
		<EmbeddedResource Include="ProductSamples\SyntaxEditorSamples\Languages\XmlSchemas\**\*.xslt" />
	</ItemGroup>

	<ItemGroup>
		<None Include="ProductSamples\SyntaxEditorSamples\Languages\Projects\**\*.langproj" />
	</ItemGroup>

	<!-- Define Actipro assembly references -->
	<Import Project="ActiproSoftware.References.props" />

</Project>